version: '3.8'


services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
      network: default
    depends_on:
      - tgbot-main-db
      - tgbot-lang-sessions
      - tgbot-chat-states

  tgbot-lang-sessions:
    container_name: tgbot-lang-sessions
    image: redis:7-alpine
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis_lang_sessions.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default

  tgbot-chat-states:
    container_name: tgbot-chat-states
    image: redis:7-alpine
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6378:6379"
    volumes:
      - ./docker/redis/redis_chat_states.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default

  tgbot-main-db:
    container_name: tgbot-main-db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD} 
    volumes:
      - ./docker/mariadb/db:/var/lib/mysql
      - ./docker/mariadb/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - default

networks:
  default: 
    driver: bridge
